2014/09/13 17:20:53 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[28000] [1045] Access denied for user 'root'@'localhost' (using password: YES)' in /var/www/html/yii/framework/db/CDbConnection.php:382
Stack trace:
#0 /var/www/html/yii/framework/db/CDbConnection.php(330): CDbConnection->open()
#1 /var/www/html/yii/framework/db/CDbConnection.php(308): CDbConnection->setActive(true)
#2 /var/www/html/yii/framework/base/CModule.php(387): CDbConnection->init()
#3 /var/www/html/yii/framework/base/CModule.php(103): CModule->getComponent('db')
#4 /var/www/html/yii/framework/gii/generators/model/ModelCode.php(60): CModule->__get('db')
#5 /var/www/html/yii/framework/web/CFormModel.php(39): ModelCode->init()
#6 /var/www/html/yii/framework/gii/CCodeGenerator.php(153): CFormModel->__construct()
#7 /var/www/html/yii/framework/gii/CCodeGenerator.php(63): CCodeGenerator->prepare()
#8 /var/www/html/yii/framework/web/actions/CInlineAction.php(49): CCodeGenerator->actionIndex()
#9 /var/www/html/yii/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#10 /var/www/html/yii/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#11 /var/www/html/yii/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 /var/www/html/yii/framework/web/CWebApplication.php(282): CController->run('index')
#13 /var/www/html/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('gii/model/index')
#14 /var/www/html/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#15 /var/www/html/yii/unixmen/index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/yii/unixmen/index.php?r=gii/model/index
HTTP_REFERER=http://localhost/yii/unixmen/index.php?r=gii/default/index
---
2014/09/15 19:14:17 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[42000] [1049] Unknown database 'store'' in /var/www/html/yii/framework/db/CDbConnection.php:382
Stack trace:
#0 /var/www/html/yii/framework/db/CDbConnection.php(330): CDbConnection->open()
#1 /var/www/html/yii/framework/db/CDbConnection.php(308): CDbConnection->setActive(true)
#2 /var/www/html/yii/framework/base/CModule.php(387): CDbConnection->init()
#3 /var/www/html/yii/framework/base/CModule.php(103): CModule->getComponent('db')
#4 /var/www/html/yii/framework/gii/generators/model/ModelCode.php(60): CModule->__get('db')
#5 /var/www/html/yii/framework/web/CFormModel.php(39): ModelCode->init()
#6 /var/www/html/yii/framework/gii/CCodeGenerator.php(153): CFormModel->__construct()
#7 /var/www/html/yii/framework/gii/CCodeGenerator.php(63): CCodeGenerator->prepare()
#8 /var/www/html/yii/framework/web/actions/CInlineAction.php(49): CCodeGenerator->actionIndex()
#9 /var/www/html/yii/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#10 /var/www/html/yii/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#11 /var/www/html/yii/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 /var/www/html/yii/framework/web/CWebApplication.php(282): CController->run('index')
#13 /var/www/html/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('gii/model/index')
#14 /var/www/html/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#15 /var/www/html/yii/unixmen/index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/yii/unixmen/index.php?r=gii/model/index
HTTP_REFERER=http://localhost/yii/unixmen/index.php?r=gii/default/index
---
2014/09/15 19:20:30 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[28000] [1045] Access denied for user 'root'@'localhost' (using password: YES)' in /var/www/html/yii/framework/db/CDbConnection.php:382
Stack trace:
#0 /var/www/html/yii/framework/db/CDbConnection.php(330): CDbConnection->open()
#1 /var/www/html/yii/framework/db/CDbConnection.php(308): CDbConnection->setActive(true)
#2 /var/www/html/yii/framework/base/CModule.php(387): CDbConnection->init()
#3 /var/www/html/yii/framework/base/CModule.php(103): CModule->getComponent('db')
#4 /var/www/html/yii/framework/gii/generators/model/ModelCode.php(60): CModule->__get('db')
#5 /var/www/html/yii/framework/web/CFormModel.php(39): ModelCode->init()
#6 /var/www/html/yii/framework/gii/CCodeGenerator.php(153): CFormModel->__construct()
#7 /var/www/html/yii/framework/gii/CCodeGenerator.php(63): CCodeGenerator->prepare()
#8 /var/www/html/yii/framework/web/actions/CInlineAction.php(49): CCodeGenerator->actionIndex()
#9 /var/www/html/yii/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#10 /var/www/html/yii/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#11 /var/www/html/yii/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 /var/www/html/yii/framework/web/CWebApplication.php(282): CController->run('index')
#13 /var/www/html/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('gii/model/index')
#14 /var/www/html/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#15 /var/www/html/yii/unixmen/index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/yii/unixmen/index.php?r=gii/model/index
HTTP_REFERER=http://localhost/yii/unixmen/index.php?r=gii/default/index
---
2014/09/15 19:22:13 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[28000] [1045] Access denied for user 'root'@'localhost' (using password: YES)' in /var/www/html/yii/framework/db/CDbConnection.php:382
Stack trace:
#0 /var/www/html/yii/framework/db/CDbConnection.php(330): CDbConnection->open()
#1 /var/www/html/yii/framework/db/CDbConnection.php(308): CDbConnection->setActive(true)
#2 /var/www/html/yii/framework/base/CModule.php(387): CDbConnection->init()
#3 /var/www/html/yii/framework/base/CModule.php(103): CModule->getComponent('db')
#4 /var/www/html/yii/framework/gii/generators/model/ModelCode.php(60): CModule->__get('db')
#5 /var/www/html/yii/framework/web/CFormModel.php(39): ModelCode->init()
#6 /var/www/html/yii/framework/gii/CCodeGenerator.php(153): CFormModel->__construct()
#7 /var/www/html/yii/framework/gii/CCodeGenerator.php(63): CCodeGenerator->prepare()
#8 /var/www/html/yii/framework/web/actions/CInlineAction.php(49): CCodeGenerator->actionIndex()
#9 /var/www/html/yii/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#10 /var/www/html/yii/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#11 /var/www/html/yii/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 /var/www/html/yii/framework/web/CWebApplication.php(282): CController->run('index')
#13 /var/www/html/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('gii/model/index')
#14 /var/www/html/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#15 /var/www/html/yii/unixmen/index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/yii/unixmen/index.php?r=gii/model/index
HTTP_REFERER=http://localhost/yii/unixmen/index.php?r=gii/default/index
---
2014/09/15 19:22:39 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[28000] [1045] Access denied for user 'root'@'localhost' (using password: YES)' in /var/www/html/yii/framework/db/CDbConnection.php:382
Stack trace:
#0 /var/www/html/yii/framework/db/CDbConnection.php(330): CDbConnection->open()
#1 /var/www/html/yii/framework/db/CDbConnection.php(308): CDbConnection->setActive(true)
#2 /var/www/html/yii/framework/base/CModule.php(387): CDbConnection->init()
#3 /var/www/html/yii/framework/base/CModule.php(103): CModule->getComponent('db')
#4 /var/www/html/yii/framework/gii/generators/model/ModelCode.php(60): CModule->__get('db')
#5 /var/www/html/yii/framework/web/CFormModel.php(39): ModelCode->init()
#6 /var/www/html/yii/framework/gii/CCodeGenerator.php(153): CFormModel->__construct()
#7 /var/www/html/yii/framework/gii/CCodeGenerator.php(63): CCodeGenerator->prepare()
#8 /var/www/html/yii/framework/web/actions/CInlineAction.php(49): CCodeGenerator->actionIndex()
#9 /var/www/html/yii/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#10 /var/www/html/yii/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#11 /var/www/html/yii/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 /var/www/html/yii/framework/web/CWebApplication.php(282): CController->run('index')
#13 /var/www/html/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('gii/model/index')
#14 /var/www/html/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#15 /var/www/html/yii/unixmen/index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/yii/unixmen/index.php?r=gii/model/index
HTTP_REFERER=http://localhost/yii/unixmen/index.php?r=gii/default/index
---
2014/09/15 19:23:19 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[28000] [1045] Access denied for user 'root'@'localhost' (using password: YES)' in /var/www/html/yii/framework/db/CDbConnection.php:382
Stack trace:
#0 /var/www/html/yii/framework/db/CDbConnection.php(330): CDbConnection->open()
#1 /var/www/html/yii/framework/db/CDbConnection.php(308): CDbConnection->setActive(true)
#2 /var/www/html/yii/framework/base/CModule.php(387): CDbConnection->init()
#3 /var/www/html/yii/framework/base/CModule.php(103): CModule->getComponent('db')
#4 /var/www/html/yii/framework/gii/generators/model/ModelCode.php(60): CModule->__get('db')
#5 /var/www/html/yii/framework/web/CFormModel.php(39): ModelCode->init()
#6 /var/www/html/yii/framework/gii/CCodeGenerator.php(153): CFormModel->__construct()
#7 /var/www/html/yii/framework/gii/CCodeGenerator.php(63): CCodeGenerator->prepare()
#8 /var/www/html/yii/framework/web/actions/CInlineAction.php(49): CCodeGenerator->actionIndex()
#9 /var/www/html/yii/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#10 /var/www/html/yii/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#11 /var/www/html/yii/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 /var/www/html/yii/framework/web/CWebApplication.php(282): CController->run('index')
#13 /var/www/html/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('gii/model/index')
#14 /var/www/html/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#15 /var/www/html/yii/unixmen/index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/yii/unixmen/index.php?r=gii/model/index
HTTP_REFERER=http://localhost/yii/unixmen/index.php?r=gii/default/index
---
2014/09/15 20:23:02 [error] [system.db.CDbCommand] CDbCommand::fetchAll() failed: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'store.tbl_user' doesn't exist. The SQL statement executed was: SHOW FULL COLUMNS FROM `tbl_user`.
in /var/www/html/yii/unixmen/index.php (13)
2014/09/15 20:23:20 [error] [system.db.CDbCommand] CDbCommand::fetchAll() failed: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'store.tbl_user' doesn't exist. The SQL statement executed was: SHOW FULL COLUMNS FROM `tbl_user`.
in /var/www/html/yii/unixmen/index.php (13)
2014/09/15 20:24:07 [error] [system.db.CDbCommand] CDbCommand::fetchAll() failed: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'store.tbl_application' doesn't exist. The SQL statement executed was: SHOW FULL COLUMNS FROM `tbl_application`.
in /var/www/html/yii/unixmen/index.php (13)
2014/09/15 20:37:57 [error] [system.db.CDbCommand] CDbCommand::fetchAll() failed: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'store.tbl_user' doesn't exist. The SQL statement executed was: SHOW FULL COLUMNS FROM `tbl_user`.
in /var/www/html/yii/unixmen/index.php (13)
2014/09/15 22:19:56 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to find the code you requested.' in /var/www/html/yii/framework/gii/CCodeGenerator.php:90
Stack trace:
#0 /var/www/html/yii/framework/web/actions/CInlineAction.php(49): CCodeGenerator->actionCode()
#1 /var/www/html/yii/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#2 /var/www/html/yii/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#3 /var/www/html/yii/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#4 /var/www/html/yii/framework/web/CWebApplication.php(282): CController->run('code')
#5 /var/www/html/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('gii/model/code')
#6 /var/www/html/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#7 /var/www/html/yii/unixmen/index.php(13): CApplication->run()
#8 {main}
REQUEST_URI=/yii/unixmen/index.php?r=gii/model/code&id=0
HTTP_REFERER=http://localhost/yii/unixmen/index.php?r=gii/model/index
---
2014/09/15 22:54:33 [error] [system.db.CDbCommand] CDbCommand::execute() failed: SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`appstore`.`tbl_user`, CONSTRAINT `FK_profile` FOREIGN KEY (`profile`) REFERENCES `tbl_profileref` (`key`)). The SQL statement executed was: INSERT INTO `tbl_user` (`username`, `password`, `email`, `profile`, `phno`, `createdate`, `lastmodified`, `fname`, `lname`) VALUES (:yp0, :yp1, :yp2, :yp3, :yp4, :yp5, :yp6, :yp7, :yp8).
in /var/www/html/yii/unixmen/protected/controllers/UserController.php (73)
in /var/www/html/yii/unixmen/index.php (13)
2014/09/15 22:54:33 [error] [exception.CDbException] exception 'CDbException' with message 'CDbCommand failed to execute the SQL statement: SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`appstore`.`tbl_user`, CONSTRAINT `FK_profile` FOREIGN KEY (`profile`) REFERENCES `tbl_profileref` (`key`)). The SQL statement executed was: INSERT INTO `tbl_user` (`username`, `password`, `email`, `profile`, `phno`, `createdate`, `lastmodified`, `fname`, `lname`) VALUES (:yp0, :yp1, :yp2, :yp3, :yp4, :yp5, :yp6, :yp7, :yp8)' in /var/www/html/yii/framework/db/CDbCommand.php:358
Stack trace:
#0 /var/www/html/yii/framework/db/ar/CActiveRecord.php(1077): CDbCommand->execute()
#1 /var/www/html/yii/framework/db/ar/CActiveRecord.php(806): CActiveRecord->insert(NULL)
#2 /var/www/html/yii/unixmen/protected/controllers/UserController.php(73): CActiveRecord->save()
#3 /var/www/html/yii/framework/web/actions/CInlineAction.php(49): UserController->actionCreate()
#4 /var/www/html/yii/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#5 /var/www/html/yii/framework/web/filters/CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#6 /var/www/html/yii/framework/web/filters/CFilter.php(40): CFilterChain->run()
#7 /var/www/html/yii/framework/web/CController.php(1145): CFilter->filter(Object(CFilterChain))
#8 /var/www/html/yii/framework/web/filters/CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#9 /var/www/html/yii/framework/web/filters/CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#10 /var/www/html/yii/framework/web/CController.php(291): CFilterChain->run()
#11 /var/www/html/yii/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 /var/www/html/yii/framework/web/CWebApplication.php(282): CController->run('create')
#13 /var/www/html/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('user/create')
#14 /var/www/html/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#15 /var/www/html/yii/unixmen/index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/yii/unixmen/index.php?r=user/create
HTTP_REFERER=http://localhost/yii/unixmen/index.php?r=user/create
---
2014/09/17 12:53:59 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii/email".' in /var/www/html/yii/framework/web/CWebApplication.php:286
Stack trace:
#0 /var/www/html/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('gii/email')
#1 /var/www/html/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /var/www/html/yii/app8it/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yii/app8it/index.php?r=gii/email
---
2014/09/17 12:54:03 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii/user".' in /var/www/html/yii/framework/web/CWebApplication.php:286
Stack trace:
#0 /var/www/html/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('gii/user')
#1 /var/www/html/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /var/www/html/yii/app8it/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yii/app8it/index.php?r=gii/user
---
2014/09/17 15:18:05 [error] [exception.CException] exception 'CException' with message 'User and its behaviors do not have a method or closure named "findByAttribute".' in /var/www/html/yii/framework/base/CComponent.php:266
Stack trace:
#0 /var/www/html/yii/framework/db/ar/CActiveRecord.php(227): CComponent->__call('findByAttribute', Array)
#1 /var/www/html/yii/app8it/protected/components/UserIdentity.php(23): CActiveRecord->__call('findByAttribute', Array)
#2 /var/www/html/yii/app8it/protected/components/UserIdentity.php(23): User->findByAttribute(Array)
#3 /var/www/html/yii/app8it/protected/models/LoginForm.php(52): UserIdentity->authenticate()
#4 /var/www/html/yii/framework/validators/CInlineValidator.php(42): LoginForm->authenticate('password', Array)
#5 /var/www/html/yii/framework/validators/CValidator.php(213): CInlineValidator->validateAttribute(Object(LoginForm), 'password')
#6 /var/www/html/yii/framework/base/CModel.php(159): CValidator->validate(Object(LoginForm), NULL)
#7 /var/www/html/yii/app8it/protected/controllers/SiteController.php(94): CModel->validate()
#8 /var/www/html/yii/framework/web/actions/CInlineAction.php(49): SiteController->actionLogin()
#9 /var/www/html/yii/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#10 /var/www/html/yii/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#11 /var/www/html/yii/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 /var/www/html/yii/framework/web/CWebApplication.php(282): CController->run('login')
#13 /var/www/html/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('site/login')
#14 /var/www/html/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#15 /var/www/html/yii/app8it/index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/yii/app8it/index.php?r=site/login
HTTP_REFERER=http://localhost/yii/app8it/index.php?r=site/login
---
2014/09/17 15:18:34 [error] [exception.CException] exception 'CException' with message 'Property "User.Password" is not defined.' in /var/www/html/yii/framework/base/CComponent.php:130
Stack trace:
#0 /var/www/html/yii/framework/db/ar/CActiveRecord.php(145): CComponent->__get('Password')
#1 /var/www/html/yii/app8it/protected/components/UserIdentity.php(26): CActiveRecord->__get('Password')
#2 /var/www/html/yii/app8it/protected/models/LoginForm.php(52): UserIdentity->authenticate()
#3 /var/www/html/yii/framework/validators/CInlineValidator.php(42): LoginForm->authenticate('password', Array)
#4 /var/www/html/yii/framework/validators/CValidator.php(213): CInlineValidator->validateAttribute(Object(LoginForm), 'password')
#5 /var/www/html/yii/framework/base/CModel.php(159): CValidator->validate(Object(LoginForm), NULL)
#6 /var/www/html/yii/app8it/protected/controllers/SiteController.php(94): CModel->validate()
#7 /var/www/html/yii/framework/web/actions/CInlineAction.php(49): SiteController->actionLogin()
#8 /var/www/html/yii/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#9 /var/www/html/yii/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#10 /var/www/html/yii/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#11 /var/www/html/yii/framework/web/CWebApplication.php(282): CController->run('login')
#12 /var/www/html/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('site/login')
#13 /var/www/html/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#14 /var/www/html/yii/app8it/index.php(13): CApplication->run()
#15 {main}
REQUEST_URI=/yii/app8it/index.php?r=site/login
HTTP_REFERER=http://localhost/yii/app8it/index.php?r=site/login
---
2014/09/17 15:23:14 [error] [exception.CException] exception 'CException' with message 'Property "User.Password" is not defined.' in /var/www/html/yii/framework/base/CComponent.php:130
Stack trace:
#0 /var/www/html/yii/framework/db/ar/CActiveRecord.php(145): CComponent->__get('Password')
#1 /var/www/html/yii/app8it/protected/components/UserIdentity.php(26): CActiveRecord->__get('Password')
#2 /var/www/html/yii/app8it/protected/models/LoginForm.php(52): UserIdentity->authenticate()
#3 /var/www/html/yii/framework/validators/CInlineValidator.php(42): LoginForm->authenticate('password', Array)
#4 /var/www/html/yii/framework/validators/CValidator.php(213): CInlineValidator->validateAttribute(Object(LoginForm), 'password')
#5 /var/www/html/yii/framework/base/CModel.php(159): CValidator->validate(Object(LoginForm), NULL)
#6 /var/www/html/yii/app8it/protected/controllers/SiteController.php(94): CModel->validate()
#7 /var/www/html/yii/framework/web/actions/CInlineAction.php(49): SiteController->actionLogin()
#8 /var/www/html/yii/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#9 /var/www/html/yii/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#10 /var/www/html/yii/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#11 /var/www/html/yii/framework/web/CWebApplication.php(282): CController->run('login')
#12 /var/www/html/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('site/login')
#13 /var/www/html/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#14 /var/www/html/yii/app8it/index.php(13): CApplication->run()
#15 {main}
REQUEST_URI=/yii/app8it/index.php?r=site/login
HTTP_REFERER=http://localhost/yii/app8it/index.php?r=site/login
---
2014/09/17 15:37:16 [error] [exception.CException] exception 'CException' with message 'Property "User.Password" is not defined.' in /var/www/html/yii/framework/base/CComponent.php:130
Stack trace:
#0 /var/www/html/yii/framework/db/ar/CActiveRecord.php(145): CComponent->__get('Password')
#1 /var/www/html/yii/app8it/protected/components/UserIdentity.php(26): CActiveRecord->__get('Password')
#2 /var/www/html/yii/app8it/protected/models/LoginForm.php(52): UserIdentity->authenticate()
#3 /var/www/html/yii/framework/validators/CInlineValidator.php(42): LoginForm->authenticate('password', Array)
#4 /var/www/html/yii/framework/validators/CValidator.php(213): CInlineValidator->validateAttribute(Object(LoginForm), 'password')
#5 /var/www/html/yii/framework/base/CModel.php(159): CValidator->validate(Object(LoginForm), NULL)
#6 /var/www/html/yii/app8it/protected/controllers/SiteController.php(94): CModel->validate()
#7 /var/www/html/yii/framework/web/actions/CInlineAction.php(49): SiteController->actionLogin()
#8 /var/www/html/yii/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#9 /var/www/html/yii/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#10 /var/www/html/yii/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#11 /var/www/html/yii/framework/web/CWebApplication.php(282): CController->run('login')
#12 /var/www/html/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('site/login')
#13 /var/www/html/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#14 /var/www/html/yii/app8it/index.php(13): CApplication->run()
#15 {main}
REQUEST_URI=/yii/app8it/index.php?r=site/login
HTTP_REFERER=http://localhost/yii/app8it/index.php?r=site/login
---
2014/09/17 15:38:59 [error] [exception.CException] exception 'CException' with message 'Property "User.id" is not defined.' in /var/www/html/yii/framework/base/CComponent.php:130
Stack trace:
#0 /var/www/html/yii/framework/db/ar/CActiveRecord.php(145): CComponent->__get('id')
#1 /var/www/html/yii/app8it/protected/components/UserIdentity.php(30): CActiveRecord->__get('id')
#2 /var/www/html/yii/app8it/protected/models/LoginForm.php(52): UserIdentity->authenticate()
#3 /var/www/html/yii/framework/validators/CInlineValidator.php(42): LoginForm->authenticate('password', Array)
#4 /var/www/html/yii/framework/validators/CValidator.php(213): CInlineValidator->validateAttribute(Object(LoginForm), 'password')
#5 /var/www/html/yii/framework/base/CModel.php(159): CValidator->validate(Object(LoginForm), NULL)
#6 /var/www/html/yii/app8it/protected/controllers/SiteController.php(94): CModel->validate()
#7 /var/www/html/yii/framework/web/actions/CInlineAction.php(49): SiteController->actionLogin()
#8 /var/www/html/yii/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#9 /var/www/html/yii/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#10 /var/www/html/yii/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#11 /var/www/html/yii/framework/web/CWebApplication.php(282): CController->run('login')
#12 /var/www/html/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('site/login')
#13 /var/www/html/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#14 /var/www/html/yii/app8it/index.php(13): CApplication->run()
#15 {main}
REQUEST_URI=/yii/app8it/index.php?r=site/login
HTTP_REFERER=http://localhost/yii/app8it/index.php?r=site/login
---
2014/09/17 15:39:46 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "page_after_login".' in /var/www/html/yii/framework/web/CController.php:483
Stack trace:
#0 /var/www/html/yii/framework/web/CController.php(270): CController->missingAction('page_after_logi...')
#1 /var/www/html/yii/framework/web/CWebApplication.php(282): CController->run('page_after_logi...')
#2 /var/www/html/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('site/page_after...')
#3 /var/www/html/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#4 /var/www/html/yii/app8it/index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/yii/app8it/index.php?r=site/page_after_login
HTTP_REFERER=http://localhost/yii/app8it/index.php?r=site/login
---
